# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 02:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
                ('direccion', models.TextField()),
                ('horarios', models.TextField(blank=True, null=True)),
                ('celular', models.BigIntegerField(blank=True, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
