# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161203_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='celular',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='horarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
