# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161203_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150, unique=True)),
                ('autor', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
            ],
        ),
    ]
